from synapse.synapse_rust import tikv_engine as tikv_engine

def sum_as_string(a: int, b: int) -> str: ...
def get_rust_file_digest() -> str: ...
def reset_logging_config() -> None: ...
def get_rustc_version() -> str: ...
