from collections.abc import Iterable

def open_client(pd_endpoints: Iterable[str]) -> None: ...
def put(key: bytes, value: bytes) -> None: ...
def get(key: bytes) -> bytes | None: ...
def batch_get(keys: Iterable[bytes]) -> list[tuple[bytes, bytes]]: ...
def batch_put(pairs: Iterable[tuple[bytes, bytes]]) -> None: ...
def delete(key: bytes) -> None: ...
def batch_delete(keys: Iterable[bytes]) -> None: ...
def scan_prefix(prefix: bytes, limit: int) -> list[tuple[bytes, bytes]]: ...
