class CacheTracer:
    def __init__(self) -> None: ...
    def on_new(self, cache: str, key: object, value: object) -> None: ...
    def on_request(self, cache: str, key: object) -> None: ...
    def on_invalidate(self, cache: str, key: object) -> None: ...
    def on_evict(self, cache: str, key: object) -> None: ...
