[program:mas]
command=/mas/mas-cli server --config /mas/config.yaml
directory=/mas

# Only start if START_MAS=true
autostart=%(ENV_START_MAS)s

priority=5
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
