[program:mas_registration_shim]
command=/usr/local/bin/prefix-log /usr/local/bin/python3 /mas/mas_registration_shim.py

# Only start if START_MAS=true
autostart=%(ENV_START_MAS)s

priority=10
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
