from __future__ import annotations

from typing import Any

from .config import Span

class BaseReporter:
    def set_process(self, service_name: str, tags: Any, max_length: int) -> None: ...
    def report_span(self, span: Span) -> None: ...

class InMemoryReporter(BaseReporter):
    def __init__(self) -> None: ...
    def get_spans(self) -> list[Span]: ...
