on:
  push:
    branches: ["develop", "release-*"]
    paths:
      - poetry.lock
  pull_request:
    paths:
      - poetry.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-sdists:
    name: "Check locked dependencies have sdists"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'
      - run: pip install tomli
      - run: ./scripts-dev/check_locked_deps_have_sdists.py
